<?php
/**
 * Copyright (c) 2018.
 * Author: Tokapps Tm
 * Programmer: gholamreza beheshtian
 * mobile: 09353466620
 * WebSite:http://tokapps.ir
 *
 *
 */


/**
 * Created by tokapps TM.
 * Programmer: gholamreza beheshtian
 * Mobile:09353466620
 * Company Phone:05138846411
 * Site:http://tokapps.ir
 * Date: 8/12/2018
 * Time: 9:59 AM
 */

namespace YiiMan\YiiBasics\widgets\fontAwesomePicker;

use kartik\base\InputWidget;
use yii\base\Widget;

class FontAwesomeFontPickerWidget extends InputWidget
{

    public $className;


    public $label;
    public $description;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!empty($this->model)) {
            $val = $this->model->{$this->attribute};
        } else {
            $val = $this->value;
        }
        echo $this->render
        (
            'picker',
            [
                'name' => $this->name,
                'label' => $this->label,
                'description' => $this->description,
                'value' => $val,
                'view' => $this->view
            ]
        );
    }
}
