<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\lib;

use Yii;
use yii\base\Component;
use \Swift_Mailer;
use \Swift_Message;
use \Swift_SmtpTransport;

class email extends Component
{
    /**
     * @var $options \YiiMan\Setting\module\components\Options
     */
    public $options;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->options = Yii::$app->Options;
    }

    //پس از ثبت نام کاربر

    /**
     * ایمیلی که پس از ثبت نام برای کاربر ارال می گردد
     * @param $user \common\models\Users مدل کاربر
     * @return int
     */
    public function sendRegister($user)
    {
        /* @var $settings \common\models\Settings */
        /* @var $user \common\models\Users */

        $subject = 'ثبت نام';
        $message = static::replace($user, Yii::$app->Options->email_text_after_register, $subject);
        return static::send($user->email, $user->fullname, $subject, $message);
    }

    //بازیابی رمز عبور

    private function replace($user, $message, $subject)
    {
        /* @var $user \common\models\Users */
        $output = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">
<html xmlns=\"http://www.w3.org/1999/xhtml\">
    <head>
        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=".Yii::$app->charset."\" />
        <title>$subject</title>
    </head>
    <body dir=\"rtl\">
        ";
        $output .= str_replace([
            '{username}',
            '{email}',
            '{fullname}',
        ], [
            $user->username,
            $user->email,
            $user->fullname,
        ], $message);
        $output .= "
    </body>
</html>";
        return $output;
    }

    //

    private function send($email_address, $name, $subject, $message)
    {
        $encryption = '';
        $port = '';
        $server = '';
        switch (Yii::$app->Options->emailEncryptionMode) {
            case 'tls':
                $server = Yii::$app->Options->emailServerSSL;
                $encryption = 'tls';
                $port = Yii::$app->Options->emailPort;
                break;
            case 'normal':
                $server = Yii::$app->Options->emailServer;
                $encryption = null;
                $port = Yii::$app->Options->emailPortNoSSL;
                break;
        }


        $mail = Swift_SmtpTransport::newInstance($server, $port, $encryption);

        /* @var $setting \common\models\Settings */
        $mail->setUsername(Yii::$app->Options->emailUsername);
        $mail->setPassword(Yii::$app->Options->emailPassword);
        $mailer = Swift_Mailer::newInstance($mail);
        $swift_message = Swift_Message::newInstance($subject);
        $swift_message->setFrom(Yii::$app->Options->emailUsername,
            Yii::$app->Options->siteTitle.' | '.Yii::t('base', 'Support'));
        $swift_message->setTo($email_address, $name);
        $swift_message->setBody($message, 'text/html', 'UTF-8');
        return $mailer->send($swift_message);
    }

    public function sendResetPassword($user)
    {
        /* @var $settings \common\models\Settings */
        /* @var $user \common\models\Users */
        $subject = 'بازیابی رمز عبور';
        $resetLink = Yii::$app->urlManager->createAbsoluteUrl([
            'site/reset-password',
            'token' => $user->password_reset_token
        ]);
        $message = static::replace($user, "<a href=\"$resetLink\">$resetLink</a>", $subject);
        return static::send($user->email, $user->fullname, $subject, $message);
    }
}
