<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * @date_of_create: 1/11/2022 AD 20:08
 */

namespace YiiMan\YiiBasics\lib;

class Session extends \yii\web\Session
{
    public function setSavePath($value)
    {
        if (!realpath($value)) {
            @mkdir($value,0775,true);
        }
        parent::setSavePath($value); // TODO: Change the autogenerated stub
    }
}