<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace system\assets\dashboard;
	
	
	use system\lib\AssetBundle;
	use system\lib\i18n\Layout;
	use Yii;
	
	/**
	 * Main backend application asset bundle.
	 */
	class MaterialDashboardSimpleAsset extends AssetBundle {
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/files' );
			$layout           = Layout::run();
			if ( $layout == 'rtl' ) {
				$this->css[] = 'css/rtl.css';
			}
		}
		
		public $js = [
			'js/loading-bar.min.js' ,
			'js/perfectScrollbar.min.js' ,
			'js/tagsInput.min.js' ,
			'js/popper.js' ,
			'js/Tippy.js' ,
			'js/sweetalert.js' ,
			'js/bootstrap-material-design.min.js' ,
			'js/bootstrap-material-dashboard.min.js' ,
			'js/material.min.js' ,
			'js/perfect-scrollbar.jquery.min.js' ,
			'js/jquery.sharrre.js' ,
			'js/chartist.min.js' ,
			'js/material-dashboard23cd.js?v=1.2.1' ,
			'js/demo.js' ,
//			'js/sweetalert2.js' ,
			'js/dropdown.js' ,
			'js/bootstrap.timepicker.js' ,
			'js/bootstrap-datepicker.js' ,
			'js/calendar.js' ,
		];
		
		public $css =
			[
				'css/material-dashboard23cd.css?v=1.2.1' ,
				'css/font-awesome.min.css' ,
				'css/demo.css' ,
				'css/font.css' ,
				'css/bootstrap-datepicker.css' ,
				'css/bootstrap-timepicker.css' ,
				'css/google-font.css' ,
				'css/loading-bar.min.css' ,
			];
		public $depends =
			[
//				'system\assets\vue\VueAssets' ,
//				'\yii\web\JqueryAsset' ,
				'yii\web\YiiAsset' ,
//				'yii\bootstrap\BootstrapAsset' ,
			];
	}
