<?php 
 return 
[
    "start"=> "start",
    "your keyboard language must be latin"=> "your keyboard language must be latin",
    "login to admin account"=> "login to admin account",
    "please enter your account details"=> "please enter your account details",
    "email"=> "email",
    "password"=> "password",
    "Remember Me"=> "Remember Me",
    "Login"=> "Login",
    "login page title"=> "login page title",
    "this field cannot be blank"=> "this field cannot be blank",
    "Incorrect email or password."=> "Incorrect email or password.",
    "آواتار"=> "آواتار",
    "وضعیت حساب کاربری"=> "وضعیت حساب کاربری",
    "چنانچه خالی باشد، رمز عبور 123456 خواهد بود"=> "چنانچه خالی باشد، رمز عبور 123456 خواهد بود",
    "نام نمایشی"=> "نام نمایشی",
    "ایمیل"=> "ایمیل",
    "رمز عبور"=> "رمز عبور",
    "وضعیت"=> "وضعیت",
    "مسدود"=> "مسدود",
    "فعال با قابلیت ورود"=> "فعال با قابلیت ورود",
    "کاربر [nameAttribute] "=> "کاربر [nameAttribute] ",
    "کاربران ادمین"=> "کاربران ادمین",
    "ویرایش"=> "ویرایش",
    "ذخیره"=> "ذخیره",
    "ثبت کاربر"=> "ثبت کاربر",
    "افزودن کاربر جدید"=> "افزودن کاربر جدید",
    "کاربر [nameAttribute] "=> "کاربر [nameAttribute] "
];