<?php
	/**
	 * Copyright (c) 2018.
	 * Author: Tokapps Tm
	 * Programmer: gholamreza beheshtian
	 * mobile: 09353466620
	 * WebSite:http://tokapps.ir
	 *
	 *
	 */
	
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 8/16/2018
	 * Time: 4:50 AM
	 */
	
	namespace YiiMan\YiiBasics\widgets\tiny\assets;
	
	
	use yii\web\AssetBundle;
	
	class TinyAssets extends AssetBundle {
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			
			$this->sourcePath = realpath( __DIR__ . '/files' );
		}
		
		public $js =
			[
				'tinymce.min.js'
			];
		
//		public $publishOptions =
//			[
//				'forceCopy' => true
//			];
		
		public $depends = [
			'yii\web\YiiAsset' ,
			'yii\bootstrap\BootstrapAsset' ,
		];
	}
