<?php
/**
 * Copyright (c) 2018-2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 * Date: 8/16/2018
 * Time: 4:50 AM
 */

namespace YiiMan\YiiBasics\widgets\tiny\assets;


use yii\web\AssetBundle;

class TinyAssets extends AssetBundle
{
    public $js =
        [
            'tinymce.min.js'
        ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

//		public $publishOptions =
//			[
//				'forceCopy' => true
//			];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->sourcePath = realpath(__DIR__.'/files');
    }
}
