<?php
	
	namespace YiiMan\YiiBasics\modules\gallery\widgets;
	
	use system\assets\angular\AngularJsAssets;
	use YiiMan\YiiBasics\lib\View;
	use yii\bootstrap\BootstrapAsset;
	use yii\web\AssetBundle;
	use yii\web\YiiAsset;
	
	/**
	 * Created by YiiMan TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:https://yiiman.ir
	 * Date: 12/29/2018
	 * Time: 2:43 PM
	 */
	class LightBoxAssets extends \YiiMan\YiiBasics\lib\AssetBundle {

		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/lightbox' );
		}

		public $js =
			[
				'js/picturefill.js' ,
				'js/lightgallery.js' ,
				'js/lg-papaer.js',
				'js/lg-autoplay.js',
//				'js/lg-fullscreen.js',

				'js/jg-zoom.js',
				'js/lg-hash.js',
				'js/lg-share.js',
                'js/lg-remove.js',
                'js/lg-defaultbtn.js',


			];
		public $css =
			[
				'css/lightgallery.css'
			];
		

		
		public $depends =
			[
				'yii\web\YiiAsset' ,
				'yii\bootstrap\BootstrapAsset' ,
			];
		
	}
