<?php
	
	namespace YiiMan\YiiBasics\modules\gallery\widgets;
	
	use YiiMan\YiiBasics\modules\filemanager\assets\FileSelectorAsset;
	use yii\base\Widget;
	use yii\widgets\InputWidget;
	
	/**
	 * Created by YiiMan TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:https://yiiman.ir
	 * Date: 12/30/2018
	 * Time: 4:05 AM
	 */
	class MediaViewWidget extends Widget {
		public $model;
		public $attribute;
		public $count;
		
		public function run() {
			parent::run(); // TODO: Change the autogenerated stub
//			FileSelectorAsset::register( $this->view );
			echo $this->render(
				'@system/modules/gallery/widgets/views/widgetView.php' ,
				[
					'model'     => $this->model ,
					'attribute' => $this->attribute ,
					'id'        => $this->attribute ,
					'count'     => $this->count
				]
			);
		}
	}
