<?php
/*
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\modules\gallery\widgets;
	
	use YiiMan\YiiBasics\assets\angular\AngularJsAssets;
	use YiiMan\YiiBasics\lib\View;
	use yii\bootstrap\BootstrapAsset;
	use yii\web\AssetBundle;
	use yii\web\YiiAsset;
	
	/**
	 * Created by YiiMan TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:+989353466620 | +17272282283
	 *
	 * Site:https://yiiman.ir
	 * Date: 12/29/2018
	 * Time: 2:43 PM
	 */
	class OwlAssets extends AssetBundle {
		
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/owl' );
		}
		
		public $js =
			[
				'owl.carousel.min.js' ,
			];
		public $css =
			[
				'assets/owl.carousel.min.css',
				'assets/owl.theme.default.min.css',
			];
		

		
		public $depends =
			[
				'yii\web\YiiAsset' ,
				'yii\bootstrap\BootstrapAsset' ,
			];
		
	}
