<?php
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 8/20/2018
	 * Time: 12:30 PM
	 */
	namespace YiiMan\YiiBasics\widgets\homeCard;
	use yii\base\Widget;
	
	class homeCard extends Widget {
		/**
		 *
		 * @var $home \common\models\Homes
		 */
		public $home;
		
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			echo $this->render( 'card',
				[
					'home'=>$this->home
				]
				);
		}
	}
