<?php
/**
 * Copyright (c) 2022-2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 * Date: 8/20/2018
 * Time: 12:30 PM
 */

namespace YiiMan\YiiBasics\widgets\homeCard;

use yii\base\Widget;

class homeCard extends Widget
{
    /**
     * @var $home \common\models\Homes
     */
    public $home;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo $this->render('card',
            [
                'home' => $this->home
            ]
        );
    }
}
