<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

return
    [
        "start"                                                                        => "start",
        "User Assignment"                                                              => "User Assignment",
        "Assignment"                                                                   => "Assignment",
        "Update"                                                                       => "Update",
        "All"                                                                          => "All",
        "Show all data"                                                                => "Show all data",
        "Page"                                                                         => "Page",
        "Show first page data"                                                         => "Show first page data",
        "Reload Grid"                                                                  => "Reload Grid",
        "* Resize table columns just like a spreadsheet by dragging the column edges." => "* Resize table columns just like a spreadsheet by dragging the column edges.",
        "assign role to user"                                                          => "assign role to user",
        "User ID"                                                                      => "User ID",
        "Roles"                                                                        => "Roles",
        "Name"                                                                         => "Name",
        "Description"                                                                  => "Description",
        "Save"                                                                         => "Save",
        "Permisstions Manager"                                                         => "Permisstions Manager",
        "Rule Name"                                                                    => "Rule Name",
        "Data"                                                                         => "Data",
        "Permission name"                                                              => "Permission name",
        "View"                                                                         => "View",
        "Delete"                                                                       => "Delete",
        "Ok"                                                                           => "Ok",
        "Cancel"                                                                       => "Cancel",
        "Are you sure?"                                                                => "Are you sure?",
        "Are you sure want to delete this item"                                        => "Are you sure want to delete this item",
        "Create new rule"                                                              => "Create new rule",
        "Rules Manager"                                                                => "Rules Manager",
        "Class Name"                                                                   => "Class Name",
        "Roles Manager"                                                                => "Roles Manager",
        "Role name"                                                                    => "Role name",
        "Permissions"                                                                  => "Permissions",
        "create Rule"                                                                  => "create Rule",
        "(not use)"                                                                    => "(not use)",
        "Rule not exists"                                                              => "Rule not exists",
        "permissions"                                                                  => "permissions",
        "permission name"                                                              => "permission name",
        "permission description"                                                       => "permission description",
        "نام دسترسی"                                                                   => "نام دسترسی",
        "توضیحات دسترسی"                                                               => "توضیحات دسترسی",
        "Type"                                                                         => "Type",
        "Created At"                                                                   => "Created At",
        "Updated At"                                                                   => "Updated At",
        "Module En"                                                                    => "Module En",
        "Module Fa"                                                                    => "Module Fa",
        "ثبت نقش"                                                                      => "ثبت نقش",
        "نقش ها"                                                                       => "نقش ها",
        "بازنشانی جست و جو"                                                            => "بازنشانی جست و جو",
        "حذف"                                                                          => "حذف",
        "لغو"                                                                          => "لغو",
        "آیا اطمینان دارید؟"                                                           => "آیا اطمینان دارید؟",
        "آیا برای حذف این آیتم اطمینان کافی دارید؟"                                    => "آیا برای حذف این آیتم اطمینان کافی دارید؟",
        "نقش"                                                                          => "نقش",
        "کاربر"                                                                        => "کاربر",
        "تاریخ ثبت"                                                                    => "تاریخ ثبت",
        "انتساب دسترسی جدید"                                                           => "انتساب دسترسی جدید",
        "انتساب"                                                                       => "انتساب",
        "بروزرسانی"                                                                    => "بروزرسانی",
        "انتساب نقش به کاربر"                                                          => "انتساب نقش به کاربر",
        "Item Name"                                                                    => "Item Name",
        "کاربران"                                                                      => "کاربران",
        "تاریخ ایجاد"                                                                  => "تاریخ ایجاد",
        "انتساب نقش به کاربران"                                                        => "انتساب نقش به کاربران",
        "You do not have access to this page"                                          => "You do not have access to this page",
        "ثبت نقش های سیستمی"                                                           => "ثبت نقش های سیستمی",
        "Parent"                                                                       => "Parent",
        "Child"                                                                        => "Child",
        "Can access to all of the system modules"                                      => "Can access to all of the system modules"
    ];