<?php

namespace YiiMan\YiiBasics\widgets\markdown;

use yii\web\AssetBundle;

/**
 * Class MarkdownEditorAsset
 *
 * @package YiiMan\YiiBasics\widgets\markdown
 */
class MarkdownEditorAsset extends AssetBundle
{
	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
		
		$this->sourcePath = realpath( __DIR__ . '/files' );
	}

    /**
     * @var array
     */
    public $css = [
        'simplemde.min.css',
    ];

    /**
     * @var array
     */
    public $js = [
        'simplemde.min.js',
    ];

    /**
     * @var array
     */
    public $depends = [
        'yii\web\YiiAsset',
    ];
}
