<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\widgets\markdown;

use yii\web\AssetBundle;

/**
 * Class MarkdownEditorAsset
 * @package YiiMan\YiiBasics\widgets\markdown
 */
class MarkdownEditorAsset extends AssetBundle
{
    /**
     * @var array
     */
    public $css = [
        'simplemde.min.css',
    ];
    /**
     * @var array
     */
    public $js = [
        'simplemde.min.js',
    ];
    /**
     * @var array
     */
    public $depends = [
        'yii\web\YiiAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->sourcePath = realpath(__DIR__.'/files');
    }
}
