<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\assets\fonts;


use YiiMan\YiiBasics\lib\AssetBundle;
use YiiMan\YiiBasics\lib\i18n\Layout;

class FontsAssets extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = realpath(__DIR__.'/files');
//        $layout = Layout::run();
//        if ($layout == 'rtl') {
        $this->css[] = 'css/fonts.css';
//        }
    }
}
