<?php
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: ۱۷/۰۴/۲۰۲۰
	 * Time: ۰۳:۵۰ قبل‌ازظهر
	 */
	
	namespace YiiMan\YiiBasics\widgets\imageSelect2;
	
	
	use kartik\base\InputWidget;
	
	class ImageSelectWidget extends \yii\widgets\InputWidget {
		public $images = [];
        public $val;
		public function run() {
			parent::run(); // TODO: Change the autogenerated stub

			return $this->render( 'index' , [ 'images' => $this->images,'name'=>$this->name ,'id'=>$this->id,'value'=>$this->val] );
		}
	}
