<?php
/**
 * Copyright (c) 2022-2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 * Date: ۱۷/۰۴/۲۰۲۰
 * Time: ۰۳:۵۰ قبل‌ازظهر
 */

namespace YiiMan\YiiBasics\widgets\imageSelect2;


use kartik\base\InputWidget;

class ImageSelectWidget extends \yii\widgets\InputWidget
{
    public $images = [];
    public $val;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('index', [
            'images' => $this->images,
            'name'   => $this->name,
            'id'     => $this->id,
            'value'  => $this->val
        ]);
    }
}
