<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

return
    [
        "start"                                                                        => "start",
        "User Assignment"                                                              => "انتساب کاربر",
        "Assignment"                                                                   => "وظیفه",
        "Update"                                                                       => "به روز رسانی",
        "All"                                                                          => "همه",
        "Show all data"                                                                => "نمایش تمام داده ها",
        "Page"                                                                         => "صفحه",
        "Show first page data"                                                         => "نمایش داده های صفحه اول",
        "Reload Grid"                                                                  => "بارگیری مجدد شبکه",
        "* Resize table columns just like a spreadsheet by dragging the column edges." => "* با کشیدن لبه های ستون ، اندازه ستون های جدول را دقیقاً مانند صفحه گسترده تغییر دهید.",
        "assign role to user"                                                          => "اختصاص دادن نقش به کاربر",
        "User ID"                                                                      => "User ID",
        "Roles"                                                                        => "نقش ها",
        "Name"                                                                         => "نام",
        "Description"                                                                  => "شرح",
        "Save"                                                                         => "ذخیره",
        "Permisstions Manager"                                                         => "مدیر مجوزها",
        "Rule Name"                                                                    => "نام قانون",
        "Data"                                                                         => "داده",
        "Permission name"                                                              => "نام مجوز",
        "View"                                                                         => "بازبینی",
        "Delete"                                                                       => "حذف",
        "Ok"                                                                           => "تایید",
        "Cancel"                                                                       => "لغو",
        "Are you sure?"                                                                => "آیا اطمینان دارید؟",
        "Are you sure want to delete this item"                                        => "برای حذف این مورد اطمینان دارید؟",
        "Create new rule"                                                              => "ایجاد قانون جدید",
        "Rules Manager"                                                                => "مدیریت قوانین",
        "Class Name"                                                                   => "نام کلاس",
        "Roles Manager"                                                                => "مدیریت نقش ها",
        "Role name"                                                                    => "نام نقش",
        "Permissions"                                                                  => "مجوز ها",
        "create Rule"                                                                  => "ایجاد قانون",
        "(not use)"                                                                    => "(not use)",
        "Rule not exists"                                                              => "Rule not exists",
        "permissions"                                                                  => "permissions",
        "permission name"                                                              => "permission name",
        "permission description"                                                       => "permission description",
        "نام دسترسی"                                                                   => "نام دسترسی",
        "توضیحات دسترسی"                                                               => "توضیحات دسترسی",
        "Type"                                                                         => "Type",
        "Created At"                                                                   => "Created At",
        "Updated At"                                                                   => "Updated At",
        "Module En"                                                                    => "Module En",
        "Module Fa"                                                                    => "Module Fa",
        "ثبت نقش"                                                                      => "ثبت نقش",
        "نقش ها"                                                                       => "نقش ها",
        "بازنشانی جست و جو"                                                            => "بازنشانی جست و جو",
        "حذف"                                                                          => "حذف",
        "لغو"                                                                          => "لغو",
        "آیا اطمینان دارید؟"                                                           => "آیا اطمینان دارید؟",
        "آیا برای حذف این آیتم اطمینان کافی دارید؟"                                    => "آیا برای حذف این آیتم اطمینان کافی دارید؟",
        "نقش"                                                                          => "نقش",
        "کاربر"                                                                        => "کاربر",
        "تاریخ ثبت"                                                                    => "تاریخ ثبت",
        "انتساب دسترسی جدید"                                                           => "انتساب دسترسی جدید",
        "انتساب"                                                                       => "انتساب",
        "بروزرسانی"                                                                    => "بروزرسانی",
        "انتساب نقش به کاربر"                                                          => "انتساب نقش به کاربر",
        "Item Name"                                                                    => "Item Name",
        "کاربران"                                                                      => "کاربران",
        "تاریخ ایجاد"                                                                  => "تاریخ ایجاد",
        "انتساب نقش به کاربران"                                                        => "انتساب نقش به کاربران",
        "You do not have access to this page"                                          => "You do not have access to this page",
        "ثبت نقش های سیستمی"                                                           => "ثبت نقش های سیستمی",
        "Parent"                                                                       => "Parent",
        "Child"                                                                        => "Child",
        "Can access to all of the system modules"                                      => "Can access to all of the system modules"
    ];