<?php


namespace YiiMan\YiiBasics\modules\slider\widgets\ism;


use kartik\base\InputWidget;

class ISM_SliderWidget extends InputWidget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('index');
    }
}
