<?php

namespace YiiMan\YiiBasics\widgets\materialTimePicker;

use yii\web\AssetBundle;

/**
 * Class MarkdownEditorAsset
 *
 * @package YiiMan\YiiBasics\widgets\markdown
 */
class MaterialTimePickerAssets extends AssetBundle
{
	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
		
		$this->sourcePath = realpath( __DIR__ . '/files' );
	}

	public $css=[
		'ADM-dateTimePicker.min.css'
		];
    
    /**
     * @var array
     */
    public $js = [
        'ADM-dateTimePicker.min.js',
    ];

    /**
     * @var array
     */
    public $depends = [
        'yii\web\YiiAsset',
	    'YiiMan\YiiBasics\assets\angular\AngularJsAssets'
    ];
}
