<?php
	
	namespace YiiMan\YiiBasics\widgets\TimePicker;
	
	use yii\web\AssetBundle;
	
	/**
	 * Class MarkdownEditorAsset
	 *
	 * @package YiiMan\YiiBasics\widgets\markdown
	 */
	class TimePickerAssets extends AssetBundle {
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			
			$this->sourcePath = realpath( __DIR__ . '/files' );
		}
		
		public $css =
			[
				'css/mdDateTimePicker.css'
			];
		
		/**
		 * @var array
		 */
		public $js =
			[
				'js/moment.js' ,
				'js/draggabilly.pkgd.min.js' ,
				'js/mdDateTimePicker.js' ,
			];
		
		/**
		 * @var array
		 */
		public $depends =
			[
				'yii\web\YiiAsset'
			];
	}
