<?php
/**
 * Copyright (c) 2018-2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 * Date: 8/16/2018
 * Time: 4:50 AM
 */

namespace YiiMan\YiiBasics\widgets\MarkDownTelegramEditor\assets;


use yii\web\AssetBundle;
use function defined;

class MarkDownTelegramEditorAssets extends \YiiMan\YiiBasics\lib\AssetBundle
{
    public $js =
        [
            'js/easymde.js'
        ];
    public $css =
        [
            'css/easymde.css'
        ];
    public $publishOptions =
        [
            'forceCopy' => true
        ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub

        $this->sourcePath = realpath(__DIR__.'/files');
    }
}
