<?php
/*
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

	/**
	 * Created by YiiMan.
	 * Programmer: gholamreza beheshtian
	 * Mobile:+989353466620 | +17272282283
	 *
	 * Site:https://yiiman.ir
	 * Date: 03/22/2020
	 * Time: 17:41 PM
	 */
	
	namespace YiiMan\YiiBasics\widgets\mobileInput\assets;
	
	
	use YiiMan\YiiBasics\lib\AssetBundle;
	
	class MobileInputAsset extends AssetBundle {
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/files' );
		}
		
		public $css =
			[
				'css/intlTelInput.css'
			];
		public $js =
			[
				'js/intlTelInput.js'
			];
		public $depends =
			[
				'\yii\web\JqueryAsset' ,
			];
	}
