<?php
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 03/22/2020
	 * Time: 17:41 PM
	 */
	
	namespace YiiMan\YiiBasics\widgets\mobileInput\assets;
	
	
	use YiiMan\YiiBasics\lib\AssetBundle;
	
	class MobileInputAsset extends AssetBundle {
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/files' );
		}
		
		public $css =
			[
				'css/intlTelInput.css'
			];
		public $js =
			[
				'js/intlTelInput.js'
			];
		public $depends =
			[
				'\yii\web\JqueryAsset' ,
			];
	}
