<?php

/**
 * Copyright (c) 2018-2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\widgets\fileUpload;

use YiiMan\YiiBasics\widgets\materialFont\assets\MaterialFontAssets;
use yii\widgets\InputWidget;

/**
 * Class FileUploadWidget
 * @package YiiMan\YiiBasics\widgets\fileUpload
 * @property string $callBack javascript callBack function name if file successfully uploaded
 */
class FileUploadWidget extends InputWidget
{

    const MODE_MATERIAL_KIT = 'materialkit';
    const MODE_DROPZONE = 'materialkit';


    /**
     * @var \yii\db\ActiveRecord
     */
//	public $model;
//	public $attribute;
//	public $view;
    public $className;
//	public $name;


    public $placeholder = 'انتخاب فایل';
    public $mode = self::MODE_MATERIAL_KIT;
    public $value = '';
    public $multiple = '';
    public $icon = 'attach_file';
    public $UploadUrl;

    /**
     * @var $callBack
     */
    public $callBack = '';

    /**
     * @var $fileTypes string like ".xls,.xlsx"
     */
    public $fileTypes = ".img,.jpeg,.jpg,.png,.gif";


    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
        if ($this->mode == self::MODE_DROPZONE) {
            MaterialFontAssets::register($this->view);
        }


        /* < Set Values > */
        {
            if (!empty($this->model->{$this->attribute})) {
                $this->value = $this->model->{$this->attribute};
            }
            $this->className = $this->model::className();
            $this->className = explode('\\', $this->className);
            $this->className = $this->className[count($this->className) - 1];

            if (empty($this->UploadUrl)) {
                $this->UploadUrl = \Yii::$app->urlManager->createUrl([\Yii::$app->controller->id.'/'.\Yii::$app->controller->action->id]);
            }
        }
        /* </ Set Values > */

        echo $this->render('view_'.$this->mode,
            [
                'class' => $this
            ]
        );
    }


}
