<?php

namespace YiiMan\YiiBasics\widgets\TreeSelector;



use YiiMan\YiiBasics\lib\AssetBundle;
use YiiMan\YiiBasics\lib\i18n\Layout;

/**
 * Class MarkdownEditorAsset
 *
 * @package YiiMan\YiiBasics\widgets\markdown
 */
class TreeSelectorAsset extends AssetBundle
{
	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
		
		$this->sourcePath = realpath( __DIR__ . '/files' );
		if (Layout::run()==='rtl'){
		    $this->css[]='rtl.css';
        }
	}

    /**
     * @var array
     */
    public $css = [
        'jquery.bonsai.css',
    ];

    /**
     * @var array
     */
    public $js = [
        'jquery.qubit.js',
        'jquery.bonsai.js',
    ];

    /**
     * @var array
     */
    public $depends = [
        'yii\web\YiiAsset',
    ];
}
