<?php 
 return 
[
    "start"=> "start",
    "Title"=> "Title",
    "Language"=> "Language",
    "Language Parent"=> "Language Parent",
    "Post Type"=> "Post Type",
    "Status"=> "Status",
    "Created At"=> "Created At",
    "Updated At"=> "Updated At",
    "Created By"=> "Created By",
    "Content"=> "Content",
    "Field Name"=> "Field Name",
    "Posttype"=> "Posttype",
    "ID"=> "ID",
    "ثبت "=> "ثبت ",
    ""=> "",
    "پست تایپ ها"=> "پست تایپ ها",
    "ویرایش این مورد"=> "ویرایش این مورد",
    "حذف این مورد"=> "حذف این مورد",
    "=>  ساندویچ"=> "=>  ساندویچ",
    "ویرایش:  "=> "ویرایش:  ",
    "بازبینی:  "=> "بازبینی:  ",
    "ویرایش : "=> "ویرایش : ",
    "بازبینی "=> "بازبینی ",
    "ویرایش"=> "ویرایش",
    "وضعیت انتشار"=> "وضعیت انتشار",
    "افزودن : "=> "افزودن : ",
    "افزودن"=> "افزودن"
];