<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * @date_of_create: 1/11/2022 AD 13:16
 */

namespace YiiMan\YiiBasics\widgets\profile\assets;

class ProfileAsset extends \YiiMan\YiiBasics\lib\AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->sourcePath = realpath(__DIR__.'/avatar');
    }
}