<?php
	/**
	 * Copyright (c) 2018.
	 * Author: Tokapps Tm
	 * Programmer: gholamreza beheshtian
	 * mobile: 09353466620
	 * WebSite:http://tokapps.ir
	 *
	 *
	 */
	
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 8/16/2018
	 * Time: 2:57 AM
	 */
	
	namespace YiiMan\YiiBasics\widgets\tiny;
	
	
	use yii\base\Widget;
	use yii\widgets\InputWidget;
	
	class tinyEditorWidget extends InputWidget {
		
		public $value;
		public function init() {
			
			
			parent::init(); // TODO: Change the autogenerated stub
			
			if (empty( $this->value)){
				if (!empty( $this->model->{$this->attribute})){
					$this->value=$this->model->{$this->attribute};
				}else{
					$this->value='';
				}
			}
		
			
			echo $this->render(
				'index' ,
				[
					'model' => $this->model ,
					'id'    => $this->id ,
					'name'  => $this->name ,
					'value' => $this->value
				]
			);
		}
	}
