<?php
/**
 * Copyright (c) 2022-2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 * Date: 03/23/2020
 * Time: 00:01 AM
 */

namespace YiiMan\YiiBasics\widgets\TippyTooltip\assets;


use YiiMan\YiiBasics\lib\AssetBundle;

class TippyAsset extends AssetBundle
{
    public $js =
        [
            'Tippy.js'
        ];
    public $css =
        [
            'tippy.css'
        ];
    public $depends = [
        '\yii\web\JqueryAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->sourcePath = realpath(__DIR__.'/files');
    }
}
