<?php
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 03/23/2020
	 * Time: 00:01 AM
	 */
	
	namespace YiiMan\YiiBasics\widgets\TippyTooltip\assets;
	
	
	use YiiMan\YiiBasics\lib\AssetBundle;
	
	class TippyAsset extends AssetBundle {
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			
			$this->sourcePath = realpath( __DIR__ . '/files' );
		}
		
		public $js =
			[
				'Tippy.js'
			];
		
		public $css =
			[
				'tippy.css'
			];
		
		public $depends = [
			'\yii\web\JqueryAsset' ,
		];
	}
