<?php
/**
 * Copyright (c) 2018-2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

/**
 * Created by PhpStorm.
 * User: amintado
 * Date: 7/24/2018
 * Time: 7:36 PM
 */

namespace YiiMan\YiiBasics\widgets\fileUpload\assets;


use yii\web\AssetBundle;

class FileUploadAsset extends AssetBundle
{
    public $js =
        [
            'dropzone.js'
        ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = realpath(__DIR__);
    }

}