<?php
/**
 * Copyright (c) 2018.
 * Author: Tokapps Tm
 * Programmer: gholamreza beheshtian
 * mobile: 09353466620
 * WebSite:http://tokapps.ir
 *
 *
 */

/**
 * Created by PhpStorm.
 * User: amintado
 * Date: 7/24/2018
 * Time: 7:36 PM
 */

namespace YiiMan\YiiBasics\widgets\fileUpload\assets;


use yii\web\AssetBundle;

class FileUploadAsset extends AssetBundle {
	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
		$this->sourcePath=realpath( __DIR__);
	}
	public $js=
		[
			'dropzone.js'
		];

	public $depends = [
		'yii\web\YiiAsset',
		'yii\bootstrap\BootstrapAsset',
	];

}