<?php
	
	namespace YiiMan\YiiBasics\modules\form\widgets;
	
	use yii\web\AssetBundle;
	
	class FormRenderAssets extends AssetBundle {
	    public function init()
        {

                $this->js[]=['form-render.min.js'];

            $this->sourcePath=__DIR__.'/files';
            parent::init(); // TODO: Change the autogenerated stub
        }

        public $js=['jquery-ui.js'];

		
		public $depends = [
//			'yii\web\YiiAsset' ,
//			'yii\bootstrap\BootstrapAsset' ,
		];
	}
