<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\modules\form\widgets;

use yii\web\AssetBundle;

class FormRenderAssets extends AssetBundle
{
    public $js = ['jquery-ui.js'];
    public $depends = [
//			'yii\web\YiiAsset' ,
//			'yii\bootstrap\BootstrapAsset' ,
    ];

    public function init()
    {

        $this->js[] = ['form-render.min.js'];

        $this->sourcePath = __DIR__.'/files';
        parent::init(); // TODO: Change the autogenerated stub
    }
}
