<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\modules\form\widgets;

use yii\web\AssetBundle;

class FormGeneratorAssets extends AssetBundle
{
    public $js = ['jquery-ui.js'];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public function init()
    {
        if (\Yii::$app->id = 'app-backend') {
            $this->js[] = ['form-builder.min.js'];
            $this->js[] = ['form-render.min.js'];
        } else {
            $this->js[] = ['form-render.min.js'];
        }
        $this->sourcePath = __DIR__.'/files';
        parent::init(); // TODO: Change the autogenerated stub
    }
}
