<?php
/**
 * Copyright (c) 2022.
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:+989353466620 | +17272282283
 * Site:https://yiiman.ir
 */

namespace YiiMan\YiiBasics\widgets;


use Yii;
use yii\base\Widget;

class MenuWidget extends Widget
{
    public $url;
    public $icon;
    public $label;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $current = '';
        if (!empty(Yii::$app->urlManager->baseUrl)) {
            $current = Yii::$app->urlManager->baseUrl.'/';
        }
        if (!empty(Yii::$app->controller->module->id)) {
            if (Yii::$app->controller->module->id != Yii::$app->id) {
                $current .= Yii::$app->controller->module->id.'/';
            }
        }
        if (!empty(Yii::$app->controller->id)) {
            $current .= Yii::$app->controller->id.'/';
        }
        if (!empty(Yii::$app->controller->action->id)) {
            $current .= Yii::$app->controller->action->id;
        }
        $url = Yii::$app->urlManager->createUrl($this->url);


        if ($url == $current) {
            $active = 'class="active"';
        } else {
            $active = '';
        }
        echo '<li '.$active.'>
					<a href="'.$url.'">
						<i class="material-icons">'.$this->icon.'</i>
						<span>'.$this->label.'</span>
					</a>
				</li>';
    }
}
